_commit: v1.12.0
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: true
helm: false
homepageDescription: Book Finder
homepageEnabled: true
homepageGroup: Media
homepageIcon: readarr
homepageName: Readarr
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: readarr.crt.house
ingName: readarr
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: ''
name: readarr
namespace: readarr
pvc: false
reloader: true
resources:
- backups.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcName: readarr
svcPortNum: 8787
upstreamURL: https://readarr.com/
url: https://github.com/charlesthomas/homelab-sonarr
