---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readarr
  namespace: readarr
spec:
  storageClassName: longhorn-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
